class GrammerData :

    follow = {
        "Program": ["$"],
        "Declaration-list": ["$","{","break",";","if","for","return","ID","(","NUM","}","+","-",],
        "Declaration": ["int","void","$","{","break",";","if","for","return","ID","(","NUM","}","+","-",],
        "Declaration-initial": ["(", ";", "[", ",", ")"],
        "Declaration-prime": ["int","void","$","{","break",";","if","for","return","ID","(","NUM","}","+","-",],
        "Var-declaration-prime": ["int","void","$","{","break",";","if","for","return","ID","(","NUM","}","+","-",],
        "Fun-declaration-prime": ["int","void","$","{","break",";","if","for","return","ID","(","NUM","}","+","-",],
        "Type-specifier": ["ID"],
        "Params": [")"],
        "Param-list": [")"],
        "Param": [",", ")"],
        "Param-prime": [",", ")"],
        "Compound-stmt": ["int","void","$","{","break",";","if","for","return","ID","(","NUM","}","+","-","endif","else",],
        "Statement-list": ["}"],
        "Statement": ["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Expression-stmt": ["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Selection-stmt":["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Else-stmt":["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Iteration-stmt": ["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Return-stmt":["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Return-stmt-prime":["{","break",";","if","for","return","ID","(","NUM","}","endif","else","+","-",],
        "Expression": [";", ")", "]", ","],
        "B": [";", ")", "]", ","],
        "H": [";", ")", "]", ","],
        "Simple-expression-zegond": [";", ")", "]", ","],
        "Simple-expression-prime": [";", ")", "]", ","],
        "C": [";", ")", "]", ","],
        "Relop": ["(", "ID", "NUM", "+", "-"],
        "Additive-expression": [";", ")", "]", ","],
        "Additive-expression-prime": ["<", "==", ";", ")", "]", ","],
        "Additive-expression-zegond": ["<", "==", ";", ")", "]", ","],
        "D": ["<", "==", ";", ")", "]", ","],
        "Addop": ["(", "ID", "NUM", "+", "-"],
        "Term": ["+", "-", ";", ")", "<", "==", "]", ","],
        "Term-prime": ["+", "-", "<", "==", ";", ")", "]", ","],
        "Term-zegond": ["+", "-", "<", "==", ";", ")", "]", ","],
        "G": ["+", "-", "<", "==", ";", ")", "]", ","],
        "Factor": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "Var-call-prime": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "Var-prime": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "Factor-prime": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
        "Factor-zegond": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
        "Args": [")"],
        "Arg-list": [")"],
        "Arg-list-prime": [")"],
    }

    first = {
        "Program": ["int", "void", "epsilon"],
        "Declaration-list": ["int", "void", "epsilon"],
        "Declaration": ["int", "void"],
        "Declaration-initial": ["int", "void"],
        "Declaration-prime": [";", "[", "("],
        "Var-declaration-prime": [";", "[", "("],
        "Fun-declaration-prime": ["("],
        "Type-specifier": ["int", "void"],
        "Params": ["int", "void"],
        "Param-list": [",", "epsilon"],
        "Param": ["int", "void"],
        "Param-prime": ["[", "epsilon"],
        "Compound-stmt": ["{"],
        "Statement-list": ["ID", ";", "NUM", "(", "{", "break", "if", "return", "for", "+", "-", "epsilon"],
        "Statement": ["ID", ";", "NUM", "(", "{", "break", "if", "return", "for", "+", "-",],
        "Expression-stmt": ["ID", ";", "NUM", "(", "break", "+", "-"],
        "Selection-stmt": ["if"],
        "Else-stmt": ["endif", "else"],
        "Iteration-stmt": ["for"],
        "Return-stmt": ["return"],
        "Return-stmt-prime": ["ID", ";", "NUM", "(", "+", "-"],
        "Expression": ["ID", "NUM", "(", "+", "-"],
        "B": ["[", "(", "=", "<", "==," "+", "-," "*", "epsilon"],
        "H": ["=", "<", "==," "+", "-," "*", "epsilon"],
        "Simple-expression-zegond": ["NUM", "(", "+", "-"],
        "Simple-expression-prime": ["(","<", "==," "+", "-," "*", "epsilon"],
        "C": ["<", "==", "epsilon"],
        "Relop": ["<", "=="],
        "Additive-expression": ["ID", "NUM", "(", "+", "-"],
        "Additive-expression-prime": ["(", "+", "-", "epsilon"],
        "Additive-expression-zegond": ["NUM", "(", "+", "-"],
        "D": ["+", "-", "epsilon"],
        "Addop": ["+", "-"],
        "Term": ["ID", "NUM", "(", "+", "-"],
        "Term-prime": ["(", "*", "epsilon"],
        "Term-zegond": ["NUM", "(", "+", "-"],
        "G": ["*", "epsilon"],
        "Signed-factor": ["ID", "NUM", "(", "+", "-"],
        "Signed-factor-prime": ["(", "epsilon"],
        "Signed-factor-zegond": ["NUM", "(", "+", "-"],
        "Factor": ["ID", "NUM", "("],
        "Var-call-prime": ["[", "(", "epsilon"],
        "Var-prime": ["[", "epsilon"],
        "Factor-prime":  ["(", "epsilon"],
        "Factor-zegond": ["NUM", "("],
        "Args": ["ID", "NUM", "(", "+", "-", "epsilon"],
        "Arg-list": ["ID", "NUM", "(", "+", "-"],
        "Arg-list-prime": [",", "epsilon"],
    }

    products = [
        ["1",  ["int", "void", "$"],"Program", ["Declaration-list", "$"]],
        ["2",  ["ID", ";", "NUM", "(", "{", "}", "break", "if", "for", "return", "+",  "-", "$"], "Declaration-list", ["epsilon"]],
        ["3",  ["int", "void"], "Declaration-list", ["Declaration", "Declaration-list"]],
        ["4",  ["int", "void"], "Declaration", ["Declaration-initial", "Declaration-prime"]],
        ["5",  ["int", "void"], "Declaration-initial", ["Type-specifier", "ID"]],
        ["6",  ["("], "Declaration-prime", ["Fun-declaration-prime"]],
        ["7",  [";", "["], "Declaration-prime", ["Var-declaration-prime"]],
        ["8",  [";"], "Var-declaration-prime", [";"]],
        ["9",  ["["], "Var-declaration-prime", ["[", "NUM", "]", ";"]],
        ["10", ["("], "Fun-declaration-prime", ["(", "Params", ")", "Compound-stmt"]],
        ["11", ["int"], "Type-specifier", ["int"]],
        ["12", ["void"], "Type-specifier", ["void"]],
        ["13", ["int"], "Params", ["int", "ID", "Param-prime", "Param-list"]],
        ["14", ["void"],"Params", ["void"]],
        ["15", [","], "Param-list", [",", "Param", "Param-list"]],
        ["16", [")"], "Param-list", ["epsilon"]],
        ["17", ["int", "void"], "Param", ["Declaration-initial", "Param-prime"]],
        ["18", ["["], "Param-prime", ["[", "]"]],
        ["19", [")", ","], "Param-prime", ["epsilon"]],
        ["20", ["{"], "Compound-stmt", ["{", "Declaration-list", "Statement-list", "}"]],
        ["21", ["NUM", "{", "break", ";", "if", "for", "return", "ID", "(", "+", "-"],  "Statement-list", ["Statement", "Statement-list"]],
        ["22", ["}"], "Statement-list", ["epsilon"]], 
        ["23", ["break", ";", "ID", "(", "NUM", "+", "-"], "Statement", ["Expression-stmt"]],
        ["24", ["{"], "Statement", ["Compound-stmt"]],
        ["25", ["if"], "Statement", ["Selection-stmt"]],
        ["26", ["for"],"Statement", ["Iteration-stmt"]],
        ["27", ["return"],  "Statement", ["Return-stmt"]],
        ["28", ["ID", "(", "NUM", "+", "-"],"Expression-stmt", ["Expression", ";"]],
        ["29", ["break"],  "Expression-stmt", ["break", ";"]],
        ["30", [";"],  "Expression-stmt", [";"]],
        ["31", ["if"],  "Selection-stmt", ["if", "(", "Expression", ")", "Statement", "Else-stmt"]],
        ["32", ["endif"], "Else-stmt", ["endif"]],
        ["33", ["else"], "Else-stmt", ["else", "Statement", "endif"]],
        ["34", ["for"],  "Iteration-stmt", ["for", "(", "Expression", ";", "Expression", ";", "Expression", ")", "Statement"]],
        ["35", ["return"], "Return-stmt", ["return", "Return-stmt-prime"]],
        ["36", [";"],"Return-stmt-prime", [";"]],
        ["37", ["ID", "(", "NUM", "+", "-"], "Return-stmt-prime", ["Expression", ";"]],
        ["38", ["(", "NUM", "+", "-"], "Expression", ["Simple-expression-zegond"]],
        ["39", ["ID"],  "Expression", ["ID", "B"]],
        ["40", ["="], "B", ["=", "Expression"]],
        ["41", ["["], "B", ["[", "Expression", "]", "H"]],
        ["42", ["(", "*", "<", "==", ";", ")", "]", ",", "+", "-"], "B", ["Simple-expression-prime"]],
        ["43", ["="],  "H", ["=", "Expression"]],
        ["44", ["*", "<", "==", ";", ")", "]", ",", "+", "-"],   "H", ["G", "D", "C"]],
        ["45", ["(", "NUM", "+", "-"],"Simple-expression-zegond", ["Additive-expression-zegond", "C"]], 
        ["46", ["(", "*", "<", "==", ";", ")", "]", ",", "+", "-"], "Simple-expression-prime", ["Additive-expression-prime", "C"]],
        ["47", ["<", "=="],  "C", ["Relop", "Additive-expression"]],
        ["48", [";", ")", "]", ","], "C", ["epsilon"]],
        ["49", ["<"], "Relop", ["<"]],
        ["50", ["=="], "Relop", ["=="]],
        ["51", ["(", "ID", "NUM", "+", "-"],  "Additive-expression", ["Term", "D"],],
        ["52", ["(", "*", "<", "==", ";" , ")", "]", ",", "+", "-"],"Additive-expression-prime", ["Term-prime", "D"]],
        ["53", ["(", "NUM", "+", "-"],  "Additive-expression-zegond", ["Term-zegond", "D"]],
        ["54", ["+", "-"], "D", ["Addop", "Term", "D"]],
        ["55", ["<", "==", ";", ")", "]", ","],"D", ["epsilon"]],
        ["56", ["+"],  "Addop", ["+"]],
        ["57", ["-"],"Addop", ["-"]],
        ["58", ["(", "ID", "NUM", "+", "-"],   "Term", ["Signed-factor", "G"]],
        ["59", ["(", "*", "+", "-", "<", "==", ";", ")", "]", ","], "Term-prime", ["Signed-factor-prime", "G"]],
        ["60", ["(", "NUM", "+", "-"],  "Term-zegond", ["Signed-factor-zegond", "G"]],
        ["61", ["*"], "G", ["*", "Signed-factor", "G"]],
        ["62", ["+", "-", "<", "==", ";", ")", "]", ","],"G", ["epsilon"]], 
        ["63", ["+"], "Signed-factor", ["+", "Factor"]], 
        ["64", ["-"], "Signed-factor", ["-", "Factor"]],
        ["65", ["NUM", "(", "ID"], "Signed-factor", ["Factor"]],
        ["66", ["]", "(", ")", ",", "*", "+", "-", "<","==", ";"],  "Signed-factor-prime", ["Factor-prime"]],
        ["67", [ "+"],   "Signed-factor-zegond", ["+", "Factor"]],
        ["68", ["-"], "Signed-factor-zegond", ["-", "Factor"]],
        ["69", ["NUM", "("], "Signed-factor-zegond", ["Factor-zegond"]],
        ["70", ["("], "Factor", ["(", "Expression", ")"]],
        ["71", ["ID"],"Factor", ["ID", "Var-call-prime"]],
        ["72", ["NUM"],  "Factor", ["NUM"]],
        ["73", ["("], "Var-call-prime", ["(", "Args", ")"]],
        ["74", [";", "[", "]", ")", ",", "*", "+", "-", "<","=="],"Var-call-prime", ["Var-prime"]],
        ["75", ["["],  "Var-prime", ["[", "Expression", "]"]],
        ["76", [";", "]", ")", ",", "*", "+", "-", "<","=="], "Var-prime", ["epsilon"]],
        ["77", ["("], "Factor-prime", ["(", "Args", ")"]],
        ["78", [";", "]", ")", ",", "*", "+", "-", "<","=="],"Factor-prime", ["epsilon"]],
        ["79", ["("],  "Factor-zegond",[ "(", "Expression", ")"]],
        ["80", ["NUM"], "Factor-zegond", ["NUM"]],
        ["81", ["ID", "NUM", "(", "+", "-"],"Args", ["Arg-list"]],
        ["82", [")"], "Args", ["epsilon"]],
        ["83", ["ID", "NUM", "(", "+", "-"],"Arg-list", ["Expression", "Arg-list-prime"]],
        ["84", [","], "Arg-list-prime", [",", "Expression", "Arg-list-prime"]],
        ["85", [")"], "Arg-list-prime", ["epsilon"]],
    ]